[package]
name = "rustpg"
version = "0.1.0"
edition = "2024"

[dependencies]
deadpool-postgres = { version = "0.14" }
tokio-postgres = { version = "0.7", features = ["with-uuid-0_8"] }
tokio = { version = "1.25", features = ["full"] }