scope: stampede
name: pg1

restapi:
  listen: 0.0.0.0:8008
  connect_address: pg1:8008

etcd3:
  hosts: pg1:2379,pg1:2379,pg2:2379
  #Even though Patroni has auto discovery of all etcd nodes, patronictl don't work that way.

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    master_start_timeout: 300
#    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        logging_collector: 'on'
        max_wal_senders: 5
        max_replication_slots: 5
        wal_log_hints: "on"
        max_wal_size: '10GB'
        archive_mode: "on"
        archive_timeout: 600s
        archive_command: "cp -f %p /home/postgres/archived/%f"
        #archive_command: pgbackrest --stanza=pg1app --log-level-stderr=info archive-push %p

      pg_hba:
      - local all all          peer
      - host replication replicator 127.0.0.1/32 trust
      - host replication replicator 192.0.0.0/8 scram-sha-256
      - host all all 0.0.0.0/0 scram-sha-256
      recovery_conf:
        restore_command: cp /home/postgres/archived/%f %p
        #restore_command: pgbackrest --stanza=pg1app archive-get %f "%p"

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

# Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh


#PostgreSQL parameters for the local node. values in this section will have higher priority than from the DCS
postgresql:
  listen: 0.0.0.0:5432
  connect_address: pg1:5432
  data_dir: "/var/lib/pgsql/16/data"
  bin_dir: "/usr/pgsql-16/bin"
#  config_dir:
  pgpass: /var/lib/pgsql/pgpass0
  authentication:
    replication:
      username: replicator
      password: vagrant
    superuser:
      username: postgres
      password: vagrant
  parameters:
    unix_socket_directories: '/var/run/postgresql'

watchdog:
  mode: off # Allowed values: off, automatic, required
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
