[package]
name = "waitforlsn"
version = "0.1.0"
edition = "2024"

[dependencies]
deadpool-postgres = { version = "0.14" }
tokio-postgres = { version = "0.7" }
tokio = { version = "1.25", features = ["full"] }
clap = { version = "4.5", features = ["derive", "env"] }
hdrhistogram = "7.5"
humantime = "2"

[profile.release]
debug = 1
