backend_clustering_mode = streaming_replication
listen_addresses = '*'
port = 9999
unix_socket_directories = '/run/pgpool-II'
enable_pool_hba = on

# --- Streaming Replication Check ---
sr_check_user = 'user2'
#sr_check_password = 'user2'
sr_check_database = 'postgres'

# --- Health Check (Optional but recommended) ---
health_check_user = 'user2'
#health_check_password = 'user2'
health_check_database = 'postgres'


# Primary Node
backend_hostname0 = '172.21.0.2'
backend_port0 = 5432
backend_weight0 = 1
backend_data_directory0 = '/var/lib/pgsql/16/data'
backend_flag0 = 'ALLOW_TO_FAILOVER'

# Standby Node
backend_hostname1 = '172.21.0.3'
backend_port1 = 5432
backend_weight1 = 1
backend_data_directory1 = '/var/lib/pgsql/16/data'
backend_flag1 = 'ALLOW_TO_FAILOVER'

